### ISSUE TITLE
Callback that fires only when an autocomplete value is selected by user?

### ISSUE THREAD

**Issue by jasonxeno** [miguelalarcos/afwrap-xautocomplete#1]
Hi,

This package is AMAZING!!! Thank you so much. I am integrating it into my app.

I'm trying to make it so if someone puts in their zip code in an address form, the state and city is automatically filled in other input fields on the page.

I thought I change the values of other input fields on the page in the value function, but the value function fires immediately when typing, not when something is actually selected in the autoform and picks the last value in the array and places them in the additional forms, city and state.

``` coffeescript
@valueZip = (x) ->
  if x
    $("[name=city]").val x.city
    $("[name=state]").val x.state
    x.zip
  else
    null

@renderZip = (x) -> Blaze.toHTMLWithData(Template.address_zip, x)
```

In another autocomplete package, meteor-autocomplete, there is a callback function that can be fired only when a value is selected:

https://github.com/mizzao/meteor-autocomplete#rule-specific-options
"callback: (optional) A function which is called when an item is selected with arguments (doc, element), corresponding to the document of the selected item and the active input field."

Is this possible to do with your package?

Thank you.

**Comment by miguelalarcos** [comment]
First of all thank you for your interest :)
I am not sure if I understand that callback (doc, element). Could you give me an example?

**Comment by jasonxeno** [comment]
Sure!

I have two form inputs.
1. Author
2. Book Title

I want to click the Book Title form field, start typing a book name, and then select one Book Title from the dropdown while there are still 10 choices.

When I select one Book Title, I want to automatically also change the value of the Author form field input, without actually touching that Author form field input. Because I just chose the Book Title, I know the author already, so I want to automatically put that in the separate Author field.

Two form fields:

``` handlebars
{{> afFieldInput  type='xautocomplete' formid="1" name='name' call='authors' xmultiple='true' valuefunction='valueAuthors' renderfunction='renderAuthors'}}</div>
{{> afFieldInput  type='xautocomplete' formid="1" name='title' call='books' xmultiple='true' valuefunction='valueBooks' renderfunction='renderBooks' callbackfunction='callbackBooks'}}</div>
```

``` coffeescript
@callbackBooks = (x) ->
     $("[name=author]").val x.author
```

So I want a callbackfunction hook that fires ONLY when I select a book title in the dropdown. In this specific case, I will put the author in the author field of the book title selected.

When I try to do this currently using the valuefunction, it fires before and without selecting an autocomplete value, so I'm guessing it needs to be a separate function for this new functionality if possible.

Does that make sense to you?

Thanks for replying! :)

**Comment by miguelalarcos** [comment]
Ok, you can use the callback like this:

``` html
{{> xautocomplete formid='2' name='surname' valuefunction='valueAuthor' renderfunction='renderAuthors' call='authors' callbackfunction='myCallback'}}
```

``` coffee
@myCallback = (x) -> console.log x.doc
```

Can you clone the repository and use it locally? I have planned changes for an upload new version to atmosphere this week.

**Comment by miguelalarcos** [comment]
Well, I have yet uploaded to atmosphere so it is not necessary to clone the project and use it locally. The version is v0.1.1, and note that it is not for production because it just have been released. With your replay it will be more near to production ready. Thanks.

**Comment by jasonxeno** [comment]
I just tested it out in my app, and the new callbackfunction works great! Thank you for making that feature! :)

I'm going to add this to many form fields in my app and help you test in general. I'll let you know if any issues come up.

Your package is very interesting, I'm going to read the package code, maybe I can help you out.

**Comment by miguelalarcos** [comment]
Thanks to you!
