### ISSUE TITLE
Feature request: prompting autocomplete with @ for Twitter

### ISSUE THREAD

**Issue by abtx** [miguelalarcos/afwrap-xautocomplete#2]
It would be great to have this feature. Cheers!

**Comment by miguelalarcos** [comment]
let me think about this. I am not sure it would be easy with the implementation at the moment.
The popup shoud show every time you type '@'?

**Comment by abtx** [comment]
Hi Miguel, I found an easy way to achieve this by prepending @ to my collection. This allows to prompt the popup with @ sign. Cheers!
