### ISSUE TITLE
autocomplete with multiple values in the input box

### ISSUE THREAD

**Issue by kaushik1979** [miguelalarcos/afwrap-xautocomplete#4]
Hi Miguel,

Can you help me understand how your plugin works for selecting multiple values in the input box?

I want to search using autocomplete for email-ids from mongo-db collection, and keep on appending to the existing value in the input box. Here is my code - 

Template -

```
<template name="quick_qoll">
  {{#autoForm schema=quickQollSchema id="quickQollForm" type="method" meteormethod="sendEmail"}}
  <fieldset>
    {{> afQuickField type="xautocomplete" formid="quickQollForm" name="name"
        renderKey="name" fieldref="email" call="fetch_my_emails" 
        renderfunction="renderQollToEmails" 
        callbackfunction="renderQollToEmailsCb"}}
    {{> afQuickField name="title"}}
    {{> afQuickField name="text"}}
    {{> afArrayField name="options"}}
    <div>
      <button type="submit" class="btn btn-primary">Submit</button>
      <button type="reset" class="btn btn-default">Reset</button>
    </div>
  </fieldset>
  {{/autoForm}}
</template>


<template name="quick_qoll_send_to">
    <td class="qoll-auto-complete">{{this.name}} <b>{{this.email}}</b></td>
</template>
```

Template Helpers - 

```
Template.quick_qoll.helpers({
  quickQollSchema: function() {
    return Schemas.quick_qoll;
  }
});

renderQollToEmails = function(x) {
    // qlog.info('called render qoll to emails method', filename);
    // console.log(x);
    return Blaze.toHTMLWithData(Template.quick_qoll_send_to, x);
    // return x.email + x.name;
};

renderQollToEmailsCb = function(x) {
    // qlog.info('Called the render-to-qoll-emails callback', filename);
    // console.log(x);
};
```

Schemas.quick_qoll -

```
Schemas.quick_qoll = new SimpleSchema({
  name: {
    type: [String],
    label: "Send To",
    regEx: SimpleSchema.RegEx.Email,
    max: 500
  },
  title: {
    type: String,
    label: "Title",
    max: 50
  },
  text: {
    type: String,
    label: "Qoll",
    min: 60,
    max: 200
  },
  options: {
    type: Array,
    label: "Qoll Options",
    optional: false
  },
  'options.$': {
    type: String
  }
});
```

**Comment by miguelalarcos** [comment]
Hi Anoop,

have you tried to add "xmultiple=true"?

If you still have problems provide me a git repo and I will try to help you.

2015-04-02 5:21 GMT+02:00 Anoop Kaushik notifications@github.com:

> Hi Miguel,
> 
> Can you help me understand how your plugin works for selecting multiple
> values in the input box?
> 
> I want to search using autocomplete for email-ids from mongo-db
> collection, and keep on appending to the existing value in the input box.
> Here is my code -
> 
> Template -
> 
> <template name="quick_qoll">
>   {{#autoForm schema=quickQollSchema id="quickQollForm" type="method" meteormethod="sendEmail"}}
>   <fieldset>
>     {{> afQuickField type="xautocomplete" formid="quickQollForm" name="name"
>         renderKey="name" fieldref="email" call="fetch_my_emails"
>         renderfunction="renderQollToEmails"
>         callbackfunction="renderQollToEmailsCb"}}
>     {{> afQuickField name="title"}}
>     {{> afQuickField name="text"}}
>     {{> afArrayField name="options"}}
>     <div>
>       <button type="submit" class="btn btn-primary">Submit</button>
>       <button type="reset" class="btn btn-default">Reset</button>
>     </div>
>   </fieldset>
>   {{/autoForm}}
> </template>
> 
> <template name="quick_qoll_send_to">
>     <td class="qoll-auto-complete">{{this.name}} <b>{{this.email}}</b></td>
> </template>
> 
> Template Helpers -
> 
> Template.quick_qoll.helpers({
>   quickQollSchema: function() {
>     return Schemas.quick_qoll;
>   }
> });
> 
> renderQollToEmails = function(x) {
>     // qlog.info('called render qoll to emails method', filename);
>     // console.log(x);
>     return Blaze.toHTMLWithData(Template.quick_qoll_send_to, x);
>     // return x.email + x.name;
> };
> 
> renderQollToEmailsCb = function(x) {
>     // qlog.info('Called the render-to-qoll-emails callback', filename);
>     // console.log(x);
> };
> 
> Schemas.quick_qoll -
> 
> Schemas.quick_qoll = new SimpleSchema({
>   name: {
>     type: [String],
>     label: "Send To",
>     regEx: SimpleSchema.RegEx.Email,
>     max: 500
>   },
>   title: {
>     type: String,
>     label: "Title",
>     max: 50
>   },
>   text: {
>     type: String,
>     label: "Qoll",
>     min: 60,
>     max: 200
>   },
>   options: {
>     type: Array,
>     label: "Qoll Options",
>     optional: false
>   },
>   'options.$': {
>     type: String
>   }
> });
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/miguelalarcos/afwrap-xautocomplete/issues/4.

## 

[image: Miguel Ángel Alarcos Torrecillas on about.me]

Miguel Ángel Alarcos Torrecillas
about.me/miguel.alarcos
    http://about.me/miguel.alarcos

**Comment by kaushik1979** [comment]
Thanks for your prompt response. When I created the test project, I realized that xmultiple was working in my project, it is just that the text-color was white. changing that to black made it appear.

I still have created the project just in case it can be of help to someone.

https://github.com/kaushik1979/xauto_test

**Comment by kaushik1979** [comment]
On a different note, can you tell me what icon package I am supposed to use? The delete buttons do not appear in xmultiple mode. I can see the placeholder but just dont see the icons.

```
<div class="xmultiple">
                <span class="ui label">krishna.chandra@gmail.com <i value="abc.xyz@gmail.com" class="delete icon xclose"></i></span>
        </div>
```

**Comment by miguelalarcos** [comment]
try with semantic-ui (css) and let me know if all is ok

**Comment by miguelalarcos** [comment]
I used nooitaf semantic ui, but it is deprecated.
May be you have to use this:
meteor add semantic:ui-icon

**Comment by kaushik1979** [comment]
Hi Miguel,

Thanks very much for your help.

<b>meteor add semantic:ui-icon</b> worked.

xautocomplete works like a charm and I plan to change all autocomplete functionalities in my project with it :).

Marking this issue closed now.

**Comment by miguelalarcos** [comment]
Thanks for your words.
