### ISSUE TITLE
\"Value must be a string\" error

### ISSUE THREAD

**Issue by kaushik1979** [miguelalarcos/afwrap-xautocomplete#5]
Hi Miguel,

When I select a new value in the xautocomplete and hit submit, it throws a validation error. Can you tell me how can I get through this? You can use the following code to reproduce this - 

https://github.com/kaushik1979/xauto_test
![screen shot 2015-04-06 at 11 15 36 pm](https://cloud.githubusercontent.com/assets/5226156/7016480/f358c8fc-dcb2-11e4-821e-fb6642e72a9b.png)

**Comment by miguelalarcos** [comment]
In your view you have `xmultiple=true` so in your model you should have `type: [String]`
Please tell me if this works.

**Comment by kaushik1979** [comment]
It worked :). Thanks.
